//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CibusMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public string CartId { get; set; }
        public int IdComboRestaurante { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int RecordId { get; set; }
    
        public virtual ComboRestaurante ComboRestaurante { get; set; }
    }
}
