//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CibusMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public int IdDetallePedido { get; set; }
        public int IdComboRestaurante { get; set; }
        public int IdPedido { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public int IdSize { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
    
        public virtual ComboRestaurante ComboRestaurante { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Size Size { get; set; }
    }
}
